### ISSUE TITLE
CSS refactoren en kleine issues fixen

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#222]
In GitLab by @se-bastiaan on Dec 8, 2016, 13:03

* [x]  Fotos lopen over elkaar bij kleiner scherm, bijvoorbeeld in de ledenlijst (#207)
* [x]  De taal-knop staat op mobiel over het logo (#202)
* [x]  Thumbnails respecteren rotatie niet (#186)
* [ ]  Meer SCSS, minder standaard CSS
* [ ]  Nutteloze onderdelen van de template weghalen zodat het style bestand minder groot en complex wordt.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 10, 2016, 12:32

marked the task **De taal-knop staat op mobiel over het logo (#202)** as completed

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 10, 2016, 12:32

marked the task **Thumbnails respecteren rotatie niet (#186)** as completed

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 21, 2016, 19:40

marked the task **Fotos lopen over elkaar bij kleiner scherm, bijvoorbeeld in de ledenlijst (#207)** as completed

**Comment by thaliawww-service** [comment]
In GitLab by @lscholten on Dec 24, 2016, 15:47

closed via commit 4ce21b2749f2d57912ea7be03991549cd87726a1

**Comment by thaliawww-service** [comment]
In GitLab by @lscholten on Dec 24, 2016, 15:47

closed via merge request !274

**Comment by thaliawww-service** [comment]
In GitLab by @lscholten on Jan 11, 2017, 19:39

mentioned in commit 4ce21b2749f2d57912ea7be03991549cd87726a1
